# Generated by Django 4.2.3 on 2023-08-07 12:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_popular_regular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
