# Generated by Django 4.2.3 on 2023-08-07 12:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_popular_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
