# Generated by Django 4.2.3 on 2023-08-15 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_regular_blogs_delete_regular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular_blogs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
