# Generated by Django 4.2.3 on 2024-01-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_contact_delete_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='regular_blogs',
            name='postDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
