# Generated by Django 4.2.3 on 2024-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_regular_blogs_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='cover',
            field=models.ImageField(null=True, upload_to='new_blog'),
        ),
    ]
